### PR TITLE
Add in overview section

### PR DESCRIPTION
**Pull request by debbly**
Overview section with cards so people know where to find information.

We received feedback from people asking for a higher level view of where they can find information and this is the first step towards making the information more accessible!

Screen Shot 2022-10-07 at 1 21 21 PM

No drastic changes to docs other than this first page.

### CODE REVIEW

**Comment by glitch003** [comment]
Screen Shot 2022-10-07 at 3 28 38 PM

Can we have it go to 2 columns on smaller screens, like mobile?  @sarahzdev @debbly

**Comment by sarahzdev** [comment]
> Screen Shot 2022-10-07 at 3 28 38 PM
> 
> Can we have it go to 2 columns on smaller screens, like mobile? @sarahzdev @debbly

updated grid styling, thanks! @glitch003

**Comment by debbly** [comment]
Looks good to merge on my end, thank you @sarahzdev :). One last pass from you @glitch003

**Comment by glitch003** [comment]
Screen Shot 2022-10-07 at 5 08 59 PM


I added some emojis to give the cards a little character.  they're kinda small tho and i'm not sure if putting them before the title or after is the right move.  @sarahzdev can you provide input here?  maybe make them a little bigger or replace them with better icons or something?

**Comment by glitch003** [comment]
also @sarahzdev if you think the emojis look fine we can leave them as is.  i don't really know how to make things look nice or how to tell when they do look nice lol.  so really just looking for at least, a second opinion from you

**Comment by sarahzdev** [comment]
> Screen Shot 2022-10-07 at 5 08 59 PM
> 
> I added some emojis to give the cards a little character. they're kinda small tho and i'm not sure if putting them before the title or after is the right move. @sarahzdev can you provide input here? maybe make them a little bigger or replace them with better icons or something?

love the pop of colors with the emojis! i think we can merge this for now and revisit the icon (maybe incorporate some of our custom-made icons) (also need to revisit the purple color in light mode) in a separate pr. lmk what ya think! @glitch003 @debbly

**Comment by kingzamzon** [comment]
I love this over view section

**Comment by debbly** [comment]
Sweet I'm merging this for now and we can revisit the style in an additional pr!

**Pull request merged**
