### PR TITLE
Update docs with new TS SDK

### PR DESCRIPTION
**Pull request by sarahzdev**
**Summary**
- Update most mentions of `lit-js-sdk` to new Lit JS SDK V2 packages
- Update all references to the old Serrano docs to the new js-sdk docs
- Removed all mentions of HTML NFT functionality as it has been deprecated in V2 (but we could re-add this content in the lit-js-sdk repo?)
- Remove mentions of `serrano` branch / tag
- Update `ALL_LIT_CHAINS` import to @lit-protocol/constants
- Add “Migrating to V2” page in `migration.md`
- Add `lit-js-sdk` deprecation notice in `installation.md`

Note: The linked examples and Replits are still using `lit-js-sdk`. Thinking of tackling those in a separate PR.

### CODE REVIEW

**Comment by Ansonhkg** [comment]
lgtm

**Comment by glitch003** [comment]
This looks great!  Thanks for getting this going @sarahzdev !  I started on this months ago on this branch, which I am sharing in case any of it is useful for you at all now, but I understand if not: https://github.com/LIT-Protocol/docs/tree/feature/new-typescript-sdk

**Review by Ansonhkg — COMMENTED** [review]
not sure if it's worth mentioning, but `lit-node-client` works on both browser and nodejs by default so no changes needed if you're already using it, the `lit-node-client-nodejs` basically is a more optimised version that stripped away browser functionalities.

**Comment by sarahzdev** [comment]
> This looks great! Thanks for getting this going @sarahzdev ! I started on this months ago on this branch, which I am sharing in case any of it is useful for you at all now, but I understand if not: https://github.com/LIT-Protocol/docs/tree/feature/new-typescript-sdk

ah thanks @glitch003 ! i copied over some changes from that branch

**Pull request merged**
